### ISSUE TITLE
🚢 Create a new release and deploy to production

### ISSUE THREAD

**Issue by macintacos** [macintacos/site#22]
## Tasks

- [x] Create a new branch: `git checkout -b GH-<this_issue_number>`
- [x] Run the following script (fill out the relevant information, edit the CHANGELOG so that it's appropriate): `yarn run release`
- [ ] After pushing, create a PR opened against `master` (not `develop`). It should have the same naming convention. Merge that PR.
- [ ] Switch to `develop` and `git rebase` the changes from `master` before resuming normal development
