### ISSUE TITLE
🚢 Create a new release and deploy to production

### ISSUE THREAD

**Issue by macintacos** [macintacos/site#27]
## Tasks

- [x] Create a new branch: `git checkout -b GH-<this_issue_number> && git push --set-upstream origin GH-<this_issue_number>`
- [x] Run the following script (fill out the relevant information, edit the CHANGELOG so that it's appropriate): `yarn run release`
- [x] After pushing, create a PR opened against `develop`. It should have the same naming convention. Squash/merge that PR as normal.
- [x] In your local repo, do the following:

```
$ git checkout develop && git pull # Get latest changes from develop
$ git checkout master && git pull # Get latest changes from master
$ git rebase develop && git push # Take all of the commits from develop, put them onto master; this maintains history
```

- [ ] Comment with a link to the release and then close the issue.

**Comment by macintacos** [comment]
Going to try this one more time

**Comment by macintacos** [comment]
Release: https://github.com/macintacos/site/releases/tag/1.0.2
